server:
  port: 8080

spring:
  main:
    allow-bean-definition-overriding: true
  thymeleaf:
    cache: false
    
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
      
  querydsl:
  packageToScan: egovframework.example.domain
  targetFolder: target/generated-sources/java

  
  